/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.xyntax;
import java.util.*;
/**
 *
 * @author nikhi
 */
public class Game extends javax.swing.JFrame {
        static int[] pcards = {0,0,0,0};
        static int[] cards1 = {0,0,0,0};
        static int[] cards2 = {0,0,0,0};
        static int[] cards3 = {0,0,0,0};
        static int[] scores = {0,0,0,0};
        static int psco = 0;
        static int cash = 1000;
        static int cashpool = 0;
        static String blank = "C:\\Users\\nikhi\\Documents\\mj\\21Images\\0.png";
        static String one = "C:\\Users\\nikhi\\Documents\\mj\\21Images\\1.png";
        static String two = "C:\\Users\\nikhi\\Documents\\mj\\21Images\\2.png";
        static String thr = "C:\\Users\\nikhi\\Documents\\mj\\21Images\\3.png";
        static String fou = "C:\\Users\\nikhi\\Documents\\mj\\21Images\\4.png";
        static String fiv = "C:\\Users\\nikhi\\Documents\\mj\\21Images\\5.png";
        static String six = "C:\\Users\\nikhi\\Documents\\mj\\21Images\\6.png";
        static String sev = "C:\\Users\\nikhi\\Documents\\mj\\21Images\\7.png";
        static String eig = "C:\\Users\\nikhi\\Documents\\mj\\21Images\\8.png";
        static String nin = "C:\\Users\\nikhi\\Documents\\mj\\21Images\\9.png";
        static String ten = "C:\\Users\\nikhi\\Documents\\mj\\21Images\\10.png";
        static String[] disp = {blank,blank,blank};
        GameFunctions gamer = new GameFunctions(pcards);
        GameFunctions gamer1 = new GameFunctions(cards1);
        GameFunctions gamer2 = new GameFunctions(cards2);
        GameFunctions gamer3 = new GameFunctions(cards3);

    /**
     * Creates new form Game
     */
    public Game() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        thiScore = new javax.swing.JLabel();
        secScore = new javax.swing.JLabel();
        firScore = new javax.swing.JLabel();
        pscore = new javax.swing.JLabel();
        ySco = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        car3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        car2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        car1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Deal");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 410, 110, -1));

        jButton2.setText("End");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 440, -1, -1));

        jButton3.setText("Bet Φ100");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 410, -1, -1));

        thiScore.setForeground(new java.awt.Color(255, 255, 255));
        thiScore.setText("?");
        getContentPane().add(thiScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 70, 20, -1));

        secScore.setForeground(new java.awt.Color(255, 255, 255));
        secScore.setText("?");
        getContentPane().add(secScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 50, 20, -1));

        firScore.setForeground(new java.awt.Color(255, 255, 255));
        firScore.setText("?");
        getContentPane().add(firScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 30, 20, -1));

        pscore.setForeground(new java.awt.Color(255, 255, 255));
        pscore.setText("?");
        getContentPane().add(pscore, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 90, 20, -1));

        ySco.setForeground(new java.awt.Color(255, 255, 255));
        ySco.setText("Your score:");
        getContentPane().add(ySco, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 90, -1, -1));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Shady Smuggler:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 70, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Han Solo:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 50, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Lando Calrissian:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 30, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Final Scores:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 10, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\nikhi\\Documents\\mj\\21Images\\logo.png")); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        car3.setIcon(new javax.swing.ImageIcon("C:\\Users\\nikhi\\Documents\\mj\\21Images\\0.png")); // NOI18N
        car3.setText("jLabel3");
        getContentPane().add(car3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 150, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Φ1000");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 450, -1, -1));

        car2.setForeground(new java.awt.Color(255, 255, 255));
        car2.setIcon(new javax.swing.ImageIcon("C:\\Users\\nikhi\\Documents\\mj\\21Images\\0.png")); // NOI18N
        car2.setText("jLabel3");
        getContentPane().add(car2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 150, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Your Cash:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 450, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\nikhi\\Documents\\mj\\21Images\\0.png")); // NOI18N
        jLabel4.setText("jLabel3");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 150, -1));

        car1.setIcon(new javax.swing.ImageIcon("C:\\Users\\nikhi\\Documents\\mj\\21Images\\0.png")); // NOI18N
        car1.setText("jLabel3");
        getContentPane().add(car1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 150, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\nikhi\\Documents\\mj\\21Images\\SabTable.png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        pcards = gamer.getCard(pcards);
        if (pcards[3] == 1){
            endGame();
        }
        disp = getDisplay(pcards);
        car1.setIcon(new javax.swing.ImageIcon(disp[0]));
        car2.setIcon(new javax.swing.ImageIcon(disp[1]));
        car3.setIcon(new javax.swing.ImageIcon(disp[2]));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        endGame();
        pcards[0] = 0;
        pcards[1] = 0;
        pcards[2] = 0;
        pcards[3] = 0;
    }//GEN-LAST:event_jButton2ActionPerformed
    public void endGame(){
        int jj;
        psco = sumUp(pcards);
        jj = psco + 10;
        if(psco < 21 && jj <= 21 && (pcards[0] == 1 || pcards[1] == 1 || pcards[2] == 1) ){
        psco += 10;
    }

        for(int i=0;i<3;i++){
            if(sumUp(cards1) < 18){
                cards1 = gamer1.getCard(cards1);
            }
            if(sumUp(cards2) < 18){
                cards2 = gamer2.getCard(cards2);
            }if(sumUp(cards3) < 18){
                cards3 = gamer3.getCard(cards3);
            }
            scores[0] = sumUp(cards1);
            scores[1] = sumUp(cards2);
            scores[2] = sumUp(cards3);
            
            firScore.setText(Integer.toString(scores[0]));
            secScore.setText(Integer.toString(scores[1]));
            thiScore.setText(Integer.toString(scores[2]));
            pscore.setText(Integer.toString(psco));
            for(int j =0;j<3;j++){
                if(scores[j] > 21){
                    scores[j] = 0;
                }
            }
            if(psco > scores[0] && psco > scores[1] && psco > scores[2] && psco < 22){
                cash += cashpool;
                cashpool = 0;
                
            }
            else{
                cashpool = 0;
            }
            jLabel7.setText("Φ " + cash);

        }
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(cash >0){
        cash -= 100;
        cashpool += 400;
        jLabel7.setText("Φ " + cash); 
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed
    int sumUp(int[] list){
        int sum = 0;
        for(int i=0;i<3;i++){
            sum += list[i];
        }
        return sum;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {


        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Game().setVisible(true);
            }
        });
    }
    String[] getDisplay(int[] cards){
        String[] dispi = {blank,blank,blank};
        for(int i=0;i < 3;i++){
            if(cards[i] == 1){
            dispi[i] = one;
        }
            if(cards[i] == 2){
            dispi[i] = two;
        }
            if(cards[i] == 3){
            dispi[i] = thr;
        }
            if(cards[i] == 4){
            dispi[i] = fou;
        }
            if(cards[i] == 5){
            dispi[i] = fiv;
        }
            if(cards[i] == 6){
            dispi[i] = six;
        }
            if(cards[i] == 7){
            dispi[i] = sev;
        }
            if(cards[i] == 8){
            dispi[i] = eig;
        }
            if(cards[i] == 9){
            dispi[i] = nin;
        }
            if(cards[i] == 10){
            dispi[i] = ten;
        }
        }
        for(int k =0;k<4;k++){
                cards1[k] = 0;
                cards2[k] = 0;
                cards3[k] = 0;
            }
        return(dispi);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel car1;
    private javax.swing.JLabel car2;
    private javax.swing.JLabel car3;
    private javax.swing.JLabel firScore;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel pscore;
    private javax.swing.JLabel secScore;
    private javax.swing.JLabel thiScore;
    private javax.swing.JLabel ySco;
    // End of variables declaration//GEN-END:variables
}
